const USER_FETCH_START = 'USER_FETCH_START';
const USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS';
const USER_FETCH_FAILED = 'USER_FETCH_FAILED';

export const userActions = {
  USER_FETCH_START,
  USER_FETCH_SUCCESS,
  USER_FETCH_FAILED,
};

const AUTH_FETCH_START = 'AUTH_FETCH_START';
const AUTH_FETCH_SUCCESS = 'AUTH_FETCH_SUCCESS';
const AUTH_FETCH_FAILED = 'AUTH_FETCH_FAILED';

export const authActions = {
  AUTH_FETCH_START,
  AUTH_FETCH_SUCCESS,
  AUTH_FETCH_FAILED,
};
